### 회원가입 테스트
POST https://book1lluwa.store/auth/signup
Content-Type: application/json

{
  "email": "abc123@google.com",
  "password": "12345"
}

### 로그인 요청
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "test@google.com",
  "password": "test1234"
}