### Refresh Test
POST http://localhost:10300/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU1NzYyNTMwLCJleHAiOjE3NTU3NjQzMzB9.n2vO8vqmlSCeaJrvjqdZBUzSH3a52QdLIFMgp8gjdlU
Cookie: ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU1NzYyNTMwLCJleHAiOjE3NTU3NjQzMzB9.n2vO8vqmlSCeaJrvjqdZBUzSH3a52QdLIFMgp8gjdlU; REFRESH_TOKEN=kr8Z16g6dUyhYMxPz7hRowYmuBq1UpID9KuUsoJXkHo
X-Forwarded-For: 127.0.0.1
User-Agent: Apache-HttpClient/4.5.14 (Java/21.0.7)
Content-Type: application/json

{
  "refreshToken": "kr8Z16g6dUyhYMxPz7hRowYmuBq1UpID9KuUsoJXkHo",
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU1NzYyNTMwLCJleHAiOjE3NTU3NjQzMzB9.n2vO8vqmlSCeaJrvjqdZBUzSH3a52QdLIFMgp8gjdlU"
}

###



