name: Deploy auth-service with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd ~/deploy/auth
          docker build -t 1lluwa-auth-service/auth-service:latest -f ./Dockerfile .

      - name: Push Docker image
        run: |
          cd ~/deploy/auth
          docker push 1lluwa-auth-service/auth-service:latest

      - name: Restart service via Rolling script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.REMOTE_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/auth
            ./start.sh